### ISSUE TITLE
IBAN Validation (Non-Norwegian)

### ISSUE THREAD

**Issue by gunnarvo** [difi/vefa-validator-conf#120]
There seems to be an error with the rules NOGOV-T10-R033 and NOGOV-T14-R016:
"IBAN numbers MUST be Alpha-2 country code, followed by two check digits and then the BBAN. Only numbers and upper case literals A-Z is allowed."

Theese rules fails for an Italian IBAN like this: IT60X0542811101000000123456
A Norwgian company could perfectly have an Italian IBAN and should be allowed to be used in EHF - between Nowregian companies.

Regards,
Gunnar Vøyenli

**Comment by TrondBjergli** [comment]
I've experienced the same issue with a customer having a british IBAN (GB99CITIxxxxx...) , and one work around, atleast for the validation service, seems to be to exclude ":extended:urn:www.difi.no:ehf:faktura:ver2.0" in the CustomizationID. 
Only if the invoice receiver is setup to receive this (believe this is an option for the customer in ELMA-register). 
Could this be a temporary solution, if this is to be fixed in an upcoming revision? 

Also, the implementation guide (both Norwegian and English version) states as following: "If account is Norwegian, BBAN should allways be submitted.", saying it could be something else than a Norwegian account.

**Comment by gunnarvo** [comment]
I think "downgrading" the CustomizationID would make it validate, but I dont think it is legal, strictly speaking, sending a Peppol BIS between two Norwegian actors. It has to be an EHF.

**Comment by SiwMeckelborg** [comment]
There will be a meeting tomorrow afternoon, where the changes in EHF this spring is discussed, so I will revert back with more info after the meeting.

**Comment by TrondBjergli** [comment]
@gunnarvo within the ELMA-register, the receivers have the option to set up to receive the peppol bis profile as well as the EHF one. 
We are already doing this with some shipping customers, and previously checked with DIFI, and gotten an OK about this.
